server {
    listen 80;
    server_name etoir.ru www.etoir.ru e-toir.ru www.e-toir.ru;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 200 'ok';
        add_header Content-Type text/plain;
    }
}